### ISSUE TITLE
The "landon_data.sql" file not included!

### ISSUE THREAD

**Issue by delete-this-account** [jeremyswann/landon#1]

**Comment by samimi-it** [comment]
The api error fixes by doing the steps as below.

1.  Run this command to pubish `dingo` with the following `Aritsan` command:
  `php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"`

Above command publishes the `dingo` as service provider by creating the `api.php` inside the config folder.

2. To use the `dingo`, the line below must be added to the `.env` file:
`API_PREFIX'=api`

Happy coding.
